create table users (
	id bigint generated by default as identity primary key,
	name varchar(255) not null,
	email varchar(255) not null unique,
	password varchar(255) not null,
	role varchar(255) not null,
	constraint users_role_check check (role in ('USER', 'SELLER', 'ADMIN'))
);

create table event (
	id bigint generated by default as identity primary key,
	name varchar(255) not null,
	venue varchar(255) not null,
	starts_at timestamp(6) not null,
	status varchar(255) not null,
	seller_id bigint references users (id)
);

create table ticket_type (
	id bigint generated by default as identity primary key,
	name varchar(255) not null,
	price numeric(19, 2) not null,
	quota integer not null,
	sold_count integer not null,
	event_id bigint not null references event (id)
);

create table orders (
	id bigint generated by default as identity primary key,
	buyer_name varchar(255) not null,
	buyer_email varchar(255) not null,
	status varchar(255) not null,
	user_id bigint not null references users (id)
);

create table ticket (
	id bigint generated by default as identity primary key,
	code varchar(255) not null unique,
	status varchar(255) not null,
	order_id bigint not null references orders (id),
	ticket_type_id bigint not null references ticket_type (id)
);

create table auth_sessions (
	id bigint generated by default as identity primary key,
	user_id bigint not null references users (id) on delete cascade,
	refresh_token_hash varchar(64) not null unique,
	expires_at timestamp(6) with time zone not null,
	revoked_at timestamp(6) with time zone
);
