alter table orders add column quantity integer not null default 0;
alter table orders add column amount numeric(19, 2) not null default 0;
alter table orders add column ticket_type_id bigint references ticket_type (id);

alter table orders drop constraint if exists orders_status_check;
alter table orders add constraint orders_status_check
	check (status in ('AWAITING_PAYMENT', 'CONFIRMED', 'CANCELLED'));

create table payments (
	id bigint generated by default as identity primary key,
	amount numeric(19, 2) not null,
	last4 varchar(4) not null,
	brand varchar(32) not null,
	created_at timestamp(6) with time zone not null,
	order_id bigint not null references orders (id)
);
