create table checkout_codes (
	id bigint generated by default as identity primary key,
	code varchar(32) not null unique
);

insert into checkout_codes (code) values ('EH-OK-001'), ('EH-OK-002'), ('DEMO2026');
